name: Python Dependency Download

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  download-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Change this to your preferred version

      - name: Install dependencies in the root folder
        run: |
          python -m pip install --upgrade pip
          pip install --target=. -r requirements.txt

      - name: List downloaded dependencies
        run: ls -l
